title: Pedro Paulo Palazzo
email: pedro.palazzo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Pesquiso arquitetura tradicional do Brasil. Professor na Universidade de
  Brasília e coordenador do grupo de pesquisa [Documentação, Modelagem e
  Conservação do Patrimônio](https://dmcpatrimonio.github.io).
baseurl: ""
url: "https://p3palazzo.github.io" 
twitter_username: p3palazzo
github_username:  p3palazzo

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata

collections:
        ensino:
        projetos:
        publicado:
        rede:

exclude:
  - docs/reveal.js/
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
