# General
title           : "Pedro P. Palazzo"
author          : "Pedro P. Palazzo"
email           : "pedro.palazzo@gmail.com"
description: >-
  Pesquiso arquitetura tradicional do Brasil. Sou professor na
  Universidade de Brasília e coordenador do grupo de pesquisa
  Documentação, Modelagem e Conservação do Patrimônio. Este site é um
  ajuda-memória para mim mesmo, registrando minha trajetória profissional
  de um jeito mais acessível do que o curriculum Lattes!
baseurl         : ""
url             : "https://p3palazzo.github.io" 
lang            : pt

# Content
include_before:
  - <div class="main-nav">
  - <a href="/cv/" alt="Curriculum Vitae" title="Curriculum Vitae"><i class="ai ai-cv ai-2x"></i></a>
  - <a href="https://orcid.org/0000-0002-0187-774X" alt="ORCID" title="ORCID"><i class="ai ai-orcid ai-2x"></i></a>
  - <a href="http://lattes.cnpq.br/5767592881382885" alt="Currículo Lattes" title="Currículo Lattes"><i class="ai ai-lattes ai-2x"></i></a>
  - <a href="https://www.cienciavitae.pt//pt/D91E-0C60-B56B" alt="Ciência Vit&ae;"><i class="ai ai-ciencia-vitae ai-2x"></i></a>
  - <a href="https://unb.academia.edu/PedroPalazzo" alt="Academia.edu"><i class="ai ai-academia ai-2x"></i></a>
  - <a href="https://www.researchgate.net/profile/Pedro-Palazzo" alt="ResearchGate" title="ResearchGate"><i class="ai ai-researchgate ai-2x"></i></a>
  - <a href="https://osf.io/79vsd/" alt="OSF" title="OSF"><i class="ai ai-osf ai-2x"></i></a>
  - </div>

collections:
  ensino:
    output      : true
    permalink   : /:collection/:name
  ext:
    output      : true
    permalink   : /:collection/:name
  org:
    output      : true
    permalink   : /:collection/:name
  pers:
  posts:
    permalink   : /:categories/:year/:month/:day/:title/
  projeto:
    output      : true
    permalink   : /:collection/:name
  rede:
    output      : true
    permalink   : /:collection/:name
  tese:

defaults:
  - scope:
      path      : ""
      type      : "ensino"
    values:
      layout    : "page"
  - scope:
      path      : ""
      type      : "ext"
    values:
      layout    : "page"
  - scope:
      path      : ""
      type      : "org"
    values:
      layout    : "page"
  - scope:
      path      : ""
      type      : "projeto"
    values:
      layout    : "page"
  - scope:
      path      : ""
      type      : "rede"
    values:
      layout    : "page"

# Template
theme           : tufte-pandoc-jekyll
minima:
  date_format   : "%d/%m/%Y"
  social_links:
    twitter     : https://twitter.com/p3palazzo
    github      : https://github.com/p3palazzo
    instagram   : https://instagram.com/p3palazzo
    flickr      : https://flickr.com/photos/arqpalazzo
    pinterest   : https://pinterest.com/p3palazzo

# Plugins
plugins:
  - jekyll-archives
  - jekyll-data
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pandoc
  - jekyll-scholar
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links

# Processing
markdown: Pandoc
pandoc:
  extensions:
    - csl                : "_csl/chicago-fullnote-bibliography-with-ibid.csl"
    - defaults           : "_spec/html.yaml"
    - section-divs
scholar:
  group_by               : type
  group_order            : ascending
  locale                 : pt
  order                  : descending
  sort_by                : date
  style                  : "chicago-fullnote-bibliography-with-ibid"
  type_aliases:
    mvbook               : book
  type_names:
    article              : "Artigos em periódicos"
    book                 : "Livros"
    incollection         : "Capítulos de livro"
    inproceedings        : "Trabalhos completos em anais de evento"
    misc                 : "Outros trabalhos técnicos"
    phdthesis            : "Orientações de Doutorado"
    thesis               : "Orientações de Mestrado"
    unpublished          : "Palestras"
  type_order:
    - book
    - article
    - incollection
    - inproceedings
    - misc
    - unpublished
    - phdthesis
    - thesis
sass_dir:
  load_paths:
    - _sass
    - assets
    - assets/css
    - assets/css-slides
    - reveal.js/css/theme/template
header_includes:
  - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

# Read
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - .vendor/
  - "default.*"
  - "*.fdb_latexmk"
  - "*.run.xml"
keep_files:
  - .git/
  - reveal.js/

# Write
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "America/Sao_Paulo"
date_format: "%d/%m/%Y"

