title: Pedro Paulo Palazzo
email: pedro.palazzo@gmail.com
description: >-
  Pesquiso arquitetura tradicional do Brasil. Sou professor na
  Universidade de Brasília e coordenador do grupo de pesquisa
  Documentação, Modelagem e Conservação do Patrimônio. Este site é um
  ajuda-memória para mim mesmo, registrando minha trajetória profissional
  de um jeito mais acessível do que o curriculum Lattes!
baseurl: ""
url: "https://p3palazzo.github.io" 
twitter_username: p3palazzo
github_username:  p3palazzo

# Build settings
markdown: kramdown
theme   : minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown

collections:
  biblio:
  ensino:
    output : true
  ext:
    output : true
  pessoa:
  projeto:
    output : true
  rede:
    output : true
  tese:

exclude:
  - docs/reveal.js/
  - spec/styles/
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
