title           : "Pedro Paulo Palazzo"
author:
  name          : "Pedro Paulo Palazzo"
  email         : "pedro.palazzo@gmail.com"
description: >-
  Pesquiso arquitetura tradicional do Brasil. Sou professor na
  Universidade de Brasília e coordenador do grupo de pesquisa
  Documentação, Modelagem e Conservação do Patrimônio. Este site é um
  ajuda-memória para mim mesmo, registrando minha trajetória profissional
  de um jeito mais acessível do que o curriculum Lattes!
baseurl         : ""
url             : "https://p3palazzo.github.io" 
lang            : pt

# Content settings {{{1
collections:
  biblio:
  ensino:
    output      : true
    permalink   : /:collection/:name
  ext:
    output      : true
    permalink   : /:collection/:name
  org:
    output      : true
    permalink   : /:collection/:name
  pers:
  posts:
    permalink   : /:categories/:year/:month/:day/:title/
  projeto:
    output      : true
    permalink   : /:collection/:name
  rede:
    output      : true
    permalink   : /:collection/:name
  tese:

defaults:
  -
    scope:
      path      : ""
      type      : "ensino"
    values:
      layout    : "page"
  -
    scope:
      path      : ""
      type      : "ext"
    values:
      layout    : "page"
  -
    scope:
      path      : ""
      type      : "org"
    values:
      layout    : "page"
  -
    scope:
      path      : ""
      type      : "projeto"
    values:
      layout    : "page"
  -
    scope:
      path      : ""
      type      : "rede"
    values:
      layout    : "page"

# Template settings {{{1
remote_theme    : p3palazzo/minima-scholar
minima:
  date_format   : "%e %b %y"
  social_links:
    twitter     : https://twitter.com/p3palazzo
    github      : https://github.com/p3palazzo/p3palazzo.github.io
    instagram   : https://instagram.com/p3palazzo
    flickr      : https://flickr.com/photos/arqpalazzo
    pinterest   :

# Build settings {{{1
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

google_analytics:
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - .vendor/

# vim: set foldmethod=marker :
