name: Website build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the custom jekyll-pandoc container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
      palazzo/jekyll-pandoc:4.2.0-2.12 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build"
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: '_site/*'
  commit:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.event_name == 'push' && github.repository == 'p3palazzo/p3palazzo.github.io' \
    env:
      commit_message: ${{ github.event.head_commit.message }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
    - name: Download site
      uses: actions/download-artifact@v2
      with:
        name: site
        path: ${{ github.workspace }}/
    - name: Commit changes to gh-pages branch
      run: |
        cd ${{ github.workspace }}
        git config --local user.email "runner@github.com"
        git config --local user.name  "Automated build"
        git add .
        git commit -m "${{ env.commit_message }}" -a || git status
        git pull --ff-only
        git push
